### PR TITLE
python scripts: Change shebang to call `python2` instead of `python`

### PR DESCRIPTION
**Pull request by nishantjr**
This allows running of IELE code on machines with both python2 and python3
installed.

### CODE REVIEW

**Comment by dwightguth** [comment]
This is not portable as not all os that install python 2 install a binary named python2. What OS are you trying to support?

**Comment by nishantjr** [comment]
hmm, I'm on archlinux. Which OS's dont do install the `python2` binary, do you know?

**Comment by dwightguth** [comment]
Mac OS for one. If I have to choose between supporting Mac OS and Arch Linux, I'm going to choose Mac OS, so if you want to support Arch Linux you need to come up with a different solution.

**Comment by nishantjr** [comment]
Sure, I'll work on getting the scripts supporting both python 2 and python 3 at some point.

**Pull request closed without merging**
