### PR TITLE
Build Nix packages in release mode

### PR DESCRIPTION
**Pull request by ttuegel**
Requires #277

### CODE REVIEW

**Comment by ttuegel** [comment]
@andreiburdusa This is ready for your review again.

**Review by andreiburdusa — COMMENTED** [review]
I tried building `iele-semantics` locally in order to make some changes and see what happens, but I got this error:
```
andrei@q:~/iele-semantics$ git submodule update --init --recursive
andrei@q:~/iele-semantics$ nix-env -f . -i
installing 'iele-assemble-exe-iele-assemble-0.0.1.0'
installing 'kiele-0.2.0'
trace: WARNING: license "LicenseRef-NCSA" not found
trace: WARNING: license "LicenseRef-NCSA" not found
trace: gitSource.nix: /nix/store/2xrvasx02sj7zc8i31k2dp8f61y6h6d2-k-f244e52 does not seem to be a git repository,
assuming it is a clean checkout.
trace: gitSource.nix: /nix/store/2xrvasx02sj7zc8i31k2dp8f61y6h6d2-k-f244e52 does not seem to be a git repository,
assuming it is a clean checkout.
trace: gitSource.nix: /nix/store/2xrvasx02sj7zc8i31k2dp8f61y6h6d2-k-f244e52 does not seem to be a git repository,
assuming it is a clean checkout.
building '/nix/store/51bhy9pz44zbcp7ayrhpzgg5m4bnmr09-user-environment.drv'...
error: packages '/nix/store/vsin1qzm9pwkpgr95q8gwa331a00prs5-kiele-0.2.0/bin/iele-assemble' and '/nix/store/90k2m9jy5wsn9lph1s97n4iraw1lsdcr-iele-assemble-exe-iele-assemble-0.0.1.0/bin/iele-assemble' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
builder for '/nix/store/51bhy9pz44zbcp7ayrhpzgg5m4bnmr09-user-environment.drv' failed with exit code 1
error: build of '/nix/store/51bhy9pz44zbcp7ayrhpzgg5m4bnmr09-user-environment.drv' failed
```
Do you know have any suggestion?
This happened on `master`, so it's not directly related to your pull request.

**Comment by ttuegel** [comment]
> Do you know have any suggestion?

Yes, you are trying to _install_ all of the packages provided by the project into your local environment. You should try `nix-build -A kiele` to just _build_ one of them.

**Comment by dwightguth** [comment]
Looks fine from my perspective, but I will let Andrei approve.

**Review by andreiburdusa — APPROVED** [review]

**Pull request merged**
